### ISSUE TITLE
Habitat code

### ISSUE THREAD

**Issue by AbdelrahmanYounes** [vdean/audio-curiosity#2]
Hello @vdean I'd like to ask you If you're planning to upload the code of Habitat soon? Thanks

**Comment by vdean** [comment]
Hi @AbdelrahmanYounes, you can now find this code on the habitat branch. Please note that this code used a previous version of habitat sound simulation, so you might need to tweak it to get it working with SoundSpaces (https://github.com/facebookresearch/sound-spaces). Thanks for your patience!

**Comment by AbdelrahmanYounes** [comment]
@vdean Thank you very much but I still can't see the Habitat branch I can only see the master branch.

**Comment by vdean** [comment]
Good catch - it should be visible now.

**Comment by AbdelrahmanYounes** [comment]
Yes, I can see it now, thanks again :)

**Comment by AbdelrahmanYounes** [comment]
@vdean Hello again, I've just a few questions,
1. I'm using Habitat v0.1.5, is it the same version that you've used?
2. I get ModuleNotFoundError in wrappers.py file line 3, from habitat_audio import * so, could you please let me know from where can I get this habitat_audio?
3. Also in wrappers.py file you get the config file from this path /home/vdean/habitat-av/configs/tasks/pointnav_nomap.yaml, Is it okay with you to upload this file? 

Thanks

**Comment by vdean** [comment]
1. I used Habitat 0.1.4
2. This is what is now called sound spaces: https://github.com/facebookresearch/sound-spaces/tree/master/soundspaces
3. You'll want to use the .yaml file from sound spaces and fill in scenes_dir to where you've downloaded the audio dataset: https://github.com/facebookresearch/sound-spaces/blob/master/configs/replica/audiopointgoal.yaml

Hope that helps!

**Comment by AbdelrahmanYounes** [comment]
Yes, that helps a lot, thanks for your quick reply.
