### ISSUE TITLE
Could you please tell me how to add noise?

### ISSUE THREAD

**Issue by Zi-Jian-Gao** [vdean/audio-curiosity#5]
which is mentioned in chapter 4.5.

**Comment by vdean** [comment]
Sure, see the use of gaussian_noise_layer here: https://github.com/vdean/audio-curiosity/blob/842bb86662331736fb8129d6847b28b978a00e9e/intrinsic_model.py#L212

**Comment by zijGao** [comment]
Thanks for your quick reply, it helps!

**Comment by zijGao** [comment]
Thanks for your quick reply, it helps!

**Comment by Zi-Jian-Gao** [comment]
Thanks for your quick reply, it helps!

**Comment by Zi-Jian-Gao** [comment]
Additionally, could you please tell me about the value of hyperparameter self.noise_multiplier in your paper?

**Comment by vdean** [comment]
That should be 0.05.

**Comment by Zi-Jian-Gao** [comment]
Thank u for great helps.
